### ISSUE TITLE
TypeError: Cannot read property 'toLowerCase' of undefined

### ISSUE THREAD

**Issue by afernandez2000** [lvlrSajjad/ignite-boilerplate-andross-typescript#3]
Executing:
ignite new CubaMess -b ignite-boilerplate-andross-typescript

This is the output:

� igniting app CubaMess
√ using the Andross Typescript ignite boilerplate
√ added React Native 0.59.2 in 38.38s
√ Choose Login Screen  · Simple Login Screen
√ Choose Main Screen  · Navigation Drawer Screen
√ added ignite-boilerplate-andross-typescript in 64.46s
an error occured while installing ignite-boilerplate-andross-typescript boilerplate.
TypeError: Cannot read property 'toLowerCase' of undefined
    at Object.install (X:\Work\CubaMess\mobile\CubaMess\node_modules\ignite-boilerplate-andross-typescript\boilerplate.js:207:79)
    at process._tickCallback (internal/process/next_tick.js:68:7)
error installing boilerplate

Ignite Doctor output:

λ ignite doctor
System
  platform           win32

  arch               x64
  cpu                12 cores                  Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
  directory          X:\Work\CubaMess\mobile

JavaScript
  node               10.13.0      c:\program files\nodejs\node.EXE
  npm                6.9.0        c:\program files\nodejs\npm.CMD
  yarn               1.12.3       c:\program files (x86)\yarn\bin\yarn.CMD

React Native
  react-native-cli   2.0.1

Ignite
  ignite             3.0.0-beta.4   c:\yarn\npm\ignite.CMD

Android
  java               -            c:\Program Files\Java\jdk1.8.0_191\bin\java.EXE
  android home       -            C:\Users\SuperAdmin\AppData\Local\Android\Sdk

**Comment by rodrigobutta** [comment]
Same here, with any of the templates

![image](https://user-images.githubusercontent.com/203718/57196852-2370f300-6f37-11e9-8b2f-d3d2760162c7.png)

**Comment by yleflour** [comment]
Found this on ignite Andross. Issue should be fixed in latest release.

https://github.com/infinitered/ignite-andross/issues/266#issuecomment-489371757

**Comment by yleflour** [comment]
It seems that this boilerplate is incompatible with Ignite 3
The PR for the original Andross boilerplate to fix this issue is the following:
https://github.com/infinitered/ignite-andross/commit/96c60fcbaebe4bf2d93cf7ee15b2da26f0a2002b

**Comment by Sundved** [comment]
PR is merged to master. But it's not working with Ignite 3.1.3 How to fix it?

**Comment by yleflour** [comment]
Sorry for not being clear enough :)

This repo is a fork of ignite-andross so I looked at it's repo for a similar issue. 
I came accross a similar issue and this PR https://github.com/infinitered/ignite-andross/commit/96c60fcbaebe4bf2d93cf7ee15b2da26f0a2002b which fixes the issue. 

Applying the same fix to ignite-boilerplate-andross-typescript should also fix it.

The issue is caused by breaking changes from Ignite 2 to Ignite 3.

Hope I made it clearer

**Comment by delkant** [comment]
hi @yleflour can you create a pull request if you have done this already?

@lvlrSajjad is that ok with you? this boilerplate looks great to me... I hope you can have a working version soon.

Thanks!

**Comment by abuslah** [comment]
any updates here?

**Comment by FrostBy** [comment]
The error still exists...
